name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm and pm2
        run: |
            npm install -g pnpm pm2

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd CI-CD/
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 restart all